# Generated by Django 4.2.17 on 2025-06-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tests', '0002_alter_author_name_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
